# Generated by Django 3.1.8 on 2021-11-16 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='user.user')),
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_accepted', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'Administrator',
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='No Title', max_length=500)),
                ('time', models.TimeField(auto_now=True)),
                ('date', models.DateField(auto_now=True)),
                ('location', models.CharField(max_length=500)),
                ('description', models.CharField(default='', max_length=1000)),
                ('status', models.BooleanField(default=True)),
                ('event_type', models.CharField(max_length=100)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_organizer', to='organizer.organizer')),
            ],
            options={
                'db_table': 'Event',
            },
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_joined', models.DateField(auto_now=True)),
                ('isAccepted', models.BooleanField(default=False)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_joined', to='administration.event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='user.user')),
            ],
            options={
                'db_table': 'Participants',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('participants_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='administration.participants')),
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500)),
                ('date_comment', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'Comment',
            },
            bases=('administration.participants',),
        ),
    ]
