# Generated by Django 3.1.7 on 2021-03-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='No Title', max_length=500),
        ),
    ]
