# Generated by Django 3.1.7 on 2021-03-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
